import mongoose from 'mongoose'
import './categoryModel';
import './subCategoryModel';


export interface IProduct {
    name: string;
    _id?: mongoose.Types.ObjectId;
    vallyId: string; //id is automatically generated by another system
    description: string;
    price: number;
    category: mongoose.Types.ObjectId | { name: string };
    subCategory: mongoose.Types.ObjectId;
    brand: string;
    sizes: string[];
    variants: string[];
    image: string; //4images per item
    stock: number;
    material: string;
    fabricSize: string;
    typeOfProduct: string;
    createdAt: Date;
    updatedAt: Date;
}



const productSchema = new mongoose.Schema<IProduct>({
    name: {
        type: String,
        required: [true, "Product name is required"],
        trim: true
    },
    vallyId: {
        type: String,
        required: true,
        unique: true
    },
    description: {
        type: String,
    },
    price: {
        type: Number,
        required: true,
    },
    category: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "Category",
        required: true
    },
    subCategory: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "SubCategory",
        // required: true
    },
    brand: {
        type: String,
        required: true,
    },
    stock: {
        type: Number,
        required: true
    },
    sizes: [
        {
            type: String,
            required: true,
            enum: {
                values: ["XS", "S", "M", "L", "XL", "XXL", "XXXL","FREE SIZE","STANDARD","NA"],
                message: "Please select a valid size"
            },
        }
    ],
    variants: [
        {
            color: {
                type: String,
                required: true,
                trim: true
            },
            images: [
                {
                    type: String,
                    required: true
                }
            ]
        }
    ],
    image:
    {
        type: String,
        required: true
    },
    material: {
        type: String,
        required: true

    },
    fabricSize: {
        type: String, //to be changed to legth{} and width{}
    },
    typeOfProduct: {
        type: String,
        required: true

    }

}, { timestamps: true })

const Product = mongoose.models.Product || mongoose.model<IProduct>("Product", productSchema)

export default Product