import mongoose from 'mongoose'
import './categoryModel';
import './subCategoryModel';


export interface IProduct {
    name: string;
    _id?: mongoose.Types.ObjectId;
    vallyId: string; //id is automatically generated by another system
    description: string;
    price: number;
    category: mongoose.Types.ObjectId | { name: string };
    subCategory: mongoose.Types.ObjectId;
    brand: string;
    sizes: string[];
    colors: string[];
    images: string[]; //4images per item
    stock: number;
    material: string;
    fabricSize: string;
    createdAt: Date;
    updatedAt: Date;
}

const productSchema = new mongoose.Schema<IProduct>({
    name: {
        type: String,
        required: [true, "Product name is required"],
        trim: true
    },
    vallyId: {
        type: String,
        required: true,
        unique: true
    },
    description: {
        type: String,
    },
    price: {
        type: Number,
        required: true,
    },
    category: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "Category",
        required: true
    },
    subCategory: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "SubCategory",
        // required: true
    },
    brand: {
        type: String,
        required: true,
    },
    stock: {
        type: Number,
        required: true
    },
    sizes: [
        {
            type: String,
            required: true,
            enum: {
                values: ["S", "M", "L", "XL", "XXL"],
                message: "Please select a valid size"
            },
        }
    ],
    colors: [
        {
            type: String,
            required: true,
            trim:true
        }

    ],
    images: [
        {
            type: String,
            required: true
        }
    ],
    //added newly
    material: {
        type: String,

    },
    fabricSize: {
        type: String, //to be changed to legth{} and width{}
    },
    
}, { timestamps: true })

const Product = mongoose.models.Product || mongoose.model<IProduct>("Product", productSchema)

export default Product