import mongoose from 'mongoose'
import './categoryModel';
import './subCategoryModel';


export interface IProduct {
    name: string;
    _id?: mongoose.Types.ObjectId;
    vallyId: string; //id is automatically generated by another system
    description: string;
    price: number;
    category: mongoose.Types.ObjectId | { name: string };
    subCategory: mongoose.Types.ObjectId;
    brand: string;
    sizes: string[];
    images: string[]; //4images per item
    stock: number;
    createdAt: Date;
    updatedAt: Date;
}

const productSchema = new mongoose.Schema<IProduct>({
    name: {
        type: String,
        required: true,
        trim: true
    },
    vallyId: {
        type: String,
        required: true
    },
    description: {
        type: String,
    },
    price: {
        type: Number,
        required: true,
    },
    category: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "Category",
        required: true
    },
    subCategory: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "SubCategory",
        // required: true
    },
    brand: {
        type: String,
        required: true,
    },
    stock: {
        type: Number,
        required: true
    },
    sizes: [
        {
            type: String,
            required: true,
            enum: ["S", "M", "L", "XL", "XXL"],
        }
    ],
    images: [
        {
            type: String,
            required: true
        }
    ]
}, { timestamps: true })


const Product = mongoose.models.Product || mongoose.model<IProduct>("Product", productSchema)

export default Product